### ISSUE TITLE
Support additional CLI arguments

### ISSUE THREAD

**Issue by peterszekeli** [DannyvanderKraan/azure-carbon-cli#1]
**TODO**

- [ ] Add filter on "ResourceType"
- [ ] Add filter on "Scope"
- [ ] Add filter on "DateRange
  - [ ]  Investigate the impact of this in the Azure Response
- [ ] Add filter on "PageSize"
