### ISSUE TITLE
Import carbon data to cost-assesssment-tool

### ISSUE THREAD

**Issue by peterszekeli** [DannyvanderKraan/azure-carbon-cli#2]
**TODO**

- [ ] Extend `AzureResource` with Carbon data
- [ ] Implement DataImporter (check `PathAzureResourceImporter`)
- [ ] Implement Commands to analyze the data (check `Commands/Analyze/AnalyzeSettings`)
